### ISSUE TITLE
Waypoint creation and removal improvements

### ISSUE THREAD

**Issue by samcrawford** [TrailRouter/public-issues#1]
A common source of mistakes for me is when I click to remove a waypoint, I sometimes miss the waypoint and end up adding another. Maybe the waypoints should be larger? Or have an invisible buffer around them to allow for clicks that miss them slightly.

**Comment by samcrawford** [comment]
Perhaps related, but consider requiring a long-press to add a waypoint on mobile - it's quite easy to accidentally add one.

**Comment by westis** [comment]
I agree that on mobile it's too easy to accidentally click on the line to create a waypoint when I actually just want to drag the map. And also, it's easy to create a new waypoint very close to another when I just want to click that waypoint.

Related to this, when I click an existing waypoint now it's simply deleted. What about a popup where I select if what I want to do is to delete it? When clicking a waypoint, I may look for other options than deleting it, such as drawing a straight line to that waypoint rather than following ways (something that now is very unintuitive and hidden in the settings). Or to see information about the distance up to that point. See Komoot for example. They even have a help link to how to create "off-grid segments".

And again just related and something that probably should get its own issue. What if I want to click on a "segment" to select for that section to be off-grid instead of following ways (or vice versa)? See "Pro tips" at https://www.komoot.com/help/routeplanner. Some ideas are worth borrowing... :D

**Comment by samcrawford** [comment]
Waypoint improvements in progress:
- Long click on the map to add a waypoint
- Long click on a waypoint to delete it
- Right click for a context menu, which will allow you to add a waypoint or add a 'direct waypoint'
- Increasing waypoint icon size
- Putting the waypoint number inside the icon

**Comment by samcrawford** [comment]
I've made quite a few changes to the UI on the development version. These are as follows:

1. Waypoints are now a bit bigger, and contain their numeric index now.
2. On desktop, you can now right click and select "Add waypoint" and "Add direct waypoint"
3. On desktop, clicking on a waypoint no longer deletes it. You now need to right click and select "Delete waypoint"
4. NOTE: On desktop, there is no change to the ability to single-click on the map to add a waypoint.
5. On mobile, clicking on the map no longer creates a waypoint. You now need to long-press and you'll be given a menu to add a waypoint or a direct waypoint.
6. On mobile, clicking on a waypoint no longer deletes it. You now need to long-press on the waypoint and you'll be given a menu allowing you to delete it.
7. Switched to Mapbox GL JS (vector based) for rendering the map. This should reduce/eliminate Mapbox fees, but it also seems a bit slower to startup.

The changes are only accessible on the development site, and only for London. Example location: https://osm.trailrouter.com/index_dev.html#wps=51.48126,0.00313%7C51.47736,0.00423%7C51.48118,0.01545&ss=&rt=false&td=0&aus=false&aus2=false&ah=false&ar=true&pga=true&im=false

@westis  - I am very keen for usability feedback on the above. I am very open to changing any of them. I'm a little concerned that it will be non-obvious to mobile users that they need to long-press on the map, so I will likely add a notification on launch. Your other suggestions haven't been forgotten (e.g. reordering waypoints), I'm just focusing on the above first.

**Comment by samcrawford** [comment]
I've put these changes live. Any feedback is still very welcome!
