### ISSUE TITLE
Elevation sources

### ISSUE THREAD

**Issue by westis** [TrailRouter/public-issues#15]
Where does elevation data come from? How is it calculated (threshold etc.)? Seems like the best DEM is Google. Is it expensive to use? Could possibly be an option for paying users later? Or if the user provide their own API key to use?

**Comment by samcrawford** [comment]
The source of elevation data is best described here: https://github.com/graphhopper/graphhopper/blob/master/docs/core/elevation.md

I don't know about the availability of any alternative sources. Whatever the source though, it couldn't be an API - the full raw data would need to be imported in order to calculate the indexes using by the routing engine (making third-party API calls every time would be extremely slow).

**Comment by samcrawford** [comment]
Going to close this as there's nothing for us to do here. Feel free to re-open if I've missed something.
